title: Ramsbury B&B
email: bookings@ramsburybandb.com
description: >- # this means to ignore newlines until "baseurl:"
  Ramsbury B&B, 33 High Street is a terraced cottage in the heart of the pretty Wiltshire village of Ramsbury.
baseurl: ""
url: "https://www.ramsburybandb.com/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima

plugins:
- jekyll-sitemap
- jekyll-seo-tag
